Dashboard refactor
DRC-COVID19/stopcoronavirus.cd pull request #150
Opened 2021-02-12 10:20 UTC by pacyL2K19

# The aim of this PR 
> Refactor the frontend of the admin dashboard using VueJs instead of Laravel Admin

## This PR contains 

>> Static pages

- Administrator routes: The main component which contains the menus and sub-routes logic 
- ListUser page: Which contains the list of all registred user with important details 
- Add User page: A form  to add new users

## Need to be added 
- Responsiveness (on the API consuption branch)
-  API consuption 
- Color and typography

2021-02-12 11:46 UTC, merki230 requested changes

2021-02-12 11:46 UTC, merki230 commented on resources/js/dashboard/pages/administrator/components/Menu.vue
> +<style>
ce style doit être scoped, il a des effets de bord sur tous les autres style de l'application 
```suggestion
<style scoped lang='scss'>
```

2021-02-12 11:46 UTC, merki230 commented on resources/js/dashboard/pages/administrator/components/Menu.vue
> +<style>
Et toujours faire du mieux que possible le sass

2021-02-12 11:46 UTC, merki230 commented on resources/js/dashboard/pages/administrator/users/Create.vue
> +        <b-form-input
tous les inputs text doivent avoir la class `input-dash`

2021-02-12 11:46 UTC, merki230 commented on resources/js/dashboard/pages/administrator/users/Create.vue
> +        label="Nom d'utilisateur:"
Dans `<b-form-group></b-form-group>` avec label, il faut dois ajouter le props `label-class` avec comme valeur `text-dash-color`

2021-02-12 11:46 UTC, merki230 commented on resources/js/dashboard/pages/administrator/users/Create.vue
> +    <b-form @submit="onSubmit" @reset="onReset" v-if="show" class="col-sm-10 col-md-6 mx-auto my-3 bg-light p-3" >
Utilisons plus tot la directive `@submit.prevent` pour ne pas envoyer le formulaire en synchronone 
```suggestion
    <b-form @submit.prevent="onSubmit" @reset="onReset"  class="col-sm-10 col-md-6 mx-auto my-3 bg-light p-3" >
```

2021-02-12 11:46 UTC, merki230 commented on resources/js/dashboard/pages/administrator/users/Create.vue
> +    <b-form @submit="onSubmit" @reset="onReset" v-if="show" class="col-sm-10 col-md-6 mx-auto my-3 bg-light p-3" >
pourquoi le `v-if="show"`

2021-02-12 11:46 UTC, merki230 commented on resources/js/dashboard/pages/administrator/users/Create.vue
> +        event.preventDefault()
Pas besoin `preventDefault`, on a déjà la directive `@submit.prevent`

2021-02-14 13:38 UTC, pacyL2K19 commented on resources/js/dashboard/pages/administrator/users/Create.vue
> +        event.preventDefault()
> compris

2021-02-14 13:38 UTC, pacyL2K19 commented on resources/js/dashboard/pages/administrator/users/Create.vue
> +    <b-form @submit="onSubmit" @reset="onReset" v-if="show" class="col-sm-10 col-md-6 mx-auto my-3 bg-light p-3" >
> Bien recu

2021-02-14 13:39 UTC, pacyL2K19 commented on resources/js/dashboard/pages/administrator/components/Header.vue
> +<style>
> Noted

2021-02-14 13:39 UTC, pacyL2K19 commented on resources/js/dashboard/pages/Administrator.vue
> +    <div class="row">
> changed

2021-02-14 13:39 UTC, closed without merging