Dashboard refactor
DRC-COVID19/stopcoronavirus.cd pull request #154
Opened 2021-02-17 11:52 UTC by pacyL2K19

# The aim of this PR

> This PR adds CRUD operation to the user admin panel 
It contains: 
- The LIst of users 
- The form to add / update user infos 
- The API consumption

To be reviewed 
:red_envelope:  @merki230

2021-02-19 17:15 UTC, merki230 requested changes

2021-02-19 17:15 UTC, merki230 commented on resources/js/dashboard/pages/administrator/components/Header.vue
> +<template>
je pense que, il faut mieux structurer le html de ce component enfin de l'utiliser presque partout sans trop d'effet de bord

2021-02-19 17:15 UTC, merki230 commented on resources/js/dashboard/pages/administrator/users/Index.vue
> +                    <Header :title="title" :iconClass="iconClass"/>
D'où l'idée de mieux structure le component `Header`

2021-02-19 17:15 UTC, merki230 commented on resources/js/dashboard/pages/administrator/users/Index.vue
> +        <b-row>
le reverse pour le mobile entre liste et formulaire

2021-02-19 17:15 UTC, merki230 commented on resources/js/dashboard/pages/administrator/users/Index.vue
> +                <ListUser :class="{hidden_list:updating}" :users="users" @onDeleteUser="deleteUser" @onUpdateUser='populateForm' />
on doit ajouter un **waiting** pendant le chargement de la liste des users

2021-02-19 17:15 UTC, merki230 commented on resources/js/dashboard/pages/administrator/users/Index.vue
> +    <b-container  fluid>
revoir la responsive de la page

2021-02-19 17:15 UTC, merki230 commented on resources/js/dashboard/pages/administrator/users/Index.vue
> +                console.log('proceeding')
on enlève les logs

2021-02-19 17:15 UTC, merki230 commented on resources/js/dashboard/pages/administrator/users/Index.vue
> +                    console.log('failed')
on envoi les exceptions vers google analytique

2021-02-22 09:26 UTC, pacyL2K19 commented on resources/js/dashboard/pages/administrator/components/MainHeader.vue
> +              :class="{ active: activeMenu == 1 }"
Oui @merki230 je l'avais mis comme classe le `activeMenu === 1` c'est juste une condition

2021-02-22 09:27 UTC, pacyL2K19 commented on resources/js/dashboard/pages/administrator/components/MainHeader.vue
> +      activeMenu: (state) => state.nav.activeMenu,
Bien recu @merki230 , je vais enlever toute cette logique

2021-02-22 09:29 UTC, pacyL2K19 commented on resources/js/dashboard/pages/administrator/components/Menu.vue
> +        <img alt="Avatar" class="avatar" src="../../../../../../public/img/admin/avatar_placeholder.png" />
Bien recu, ce menu n'est meme plus uitilisE en fait, je vais seulement le supprimer, c'etait le side bar menu

2021-02-22 09:29 UTC, pacyL2K19 commented on resources/js/dashboard/pages/administrator/components/Menu.vue
> +<template>
Non, je l'enleve

2021-02-22 09:30 UTC, pacyL2K19 commented on resources/js/dashboard/pages/administrator/components/Header.vue
> +<template>
Bien recu, je modifie

2021-02-22 09:31 UTC, pacyL2K19 commented on resources/js/dashboard/pages/administrator/users/Index.vue
> +                    console.log('failed')
Bien recu

2021-02-22 11:06 UTC, pacyL2K19 commented on resources/js/dashboard/pages/administrator/components/MainHeader.vue
> +      activeMenu: (state) => state.nav.activeMenu,
Apres avoit bien regardE j'ai constatE que cette partie est aussi importante pour reconnaitre l'utilisateur connectE

2021-02-22 13:13 UTC, merki230 requested changes

2021-02-22 13:51 UTC, merki230 requested changes

2021-02-22 13:51 UTC, merki230 commented on resources/js/dashboard/pages/administrator/components/MainHeader.vue
> +              :class="{ active: activeMenu == 1 }"
`:class="{active:route.name=="administrator.users"}`

2021-02-22 13:51 UTC, merki230 commented on resources/js/dashboard/pages/administrator/components/MainHeader.vue
> +      activeMenu: (state) => state.nav.activeMenu,
A supprimer

2021-02-22 13:51 UTC, merki230 commented on resources/js/dashboard/pages/administrator/components/MainHeader.vue
> +    ...mapMutations(["setActiveMenu"]),
A supprimer

2021-02-22 13:51 UTC, merki230 commented on resources/js/dashboard/pages/administrator/components/MainHeader.vue
> +    selectMenu(value) {
A Supprimer

2021-02-22 13:51 UTC, merki230 commented on resources/js/dashboard/pages/administrator/components/MainHeader.vue
> +b-link {
Ca va pas marcher

2021-02-22 13:51 UTC, merki230 commented on resources/js/dashboard/pages/administrator/components/MainHeader.vue
> +  b-link {
Ca va pas marcher

2021-02-22 13:51 UTC, merki230 commented on resources/js/dashboard/pages/administrator/components/Menu.vue
> +    <div class="parent" v-for="item in items" :key="item.key" @mouseover="hover = item.key" @mouseleave="hover = -1">
`v-for=(item,index) in items`

2021-02-22 13:51 UTC, merki230 commented on resources/js/dashboard/pages/administrator/components/Menu.vue
> +<template>
A supprimer

2021-03-01 14:20 UTC, merged