Situation epid
DRC-COVID19/stopcoronavirus.cd pull request #155
Opened 2021-02-22 08:58 UTC by pacyL2K19

# The aim of this PR

> This PR contains 

- List Situation: Users can view the complete list with tabulation of 15 items
- Nouvelle Situation (form) : Users can add situation epidemiologique
- Users can remove 
- Users can update 
> To be implemented 

- [ ] API consumption on the update route
- [ ]  Work on feedback after review @merki230

2021-02-23 10:18 UTC, merki230 requested changes

2021-02-23 10:18 UTC, merki230 commented on resources/js/dashboard/pages/administrator/epidemy/components/CreateSituation.vue
> +        show: true,
Il n'est utilisé nul part

2021-02-23 10:18 UTC, merki230 commented on resources/js/dashboard/pages/administrator/epidemy/components/CreateSituation.vue
> +      this.getUserRoles(),
Il n y a pas des users roles dans situation épidémiologique

2021-02-23 10:18 UTC, merki230 commented on resources/js/dashboard/pages/administrator/epidemy/components/CreateSituation.vue
> +      getUserRoles () {
Cette méthode n'a aucune utilité dans ce component

2021-02-23 10:18 UTC, merki230 commented on resources/js/dashboard/pages/administrator/epidemy/components/ListSituation.vue
> +    <b-row class="my-3 d-flex justif-content-start">
Utiliser les props de b-row si nécessaire à la place de d-flex justify-content -start

2021-02-23 10:18 UTC, merki230 commented on resources/js/dashboard/pages/administrator/epidemy/components/ListSituation.vue
> +      <b-col cols="12" md="6" class="ml-auto">
il n'est plus nécessaire

2021-02-24 09:47 UTC, pacyL2K19 commented on resources/js/dashboard/pages/administrator/epidemy/Index.vue
> +        <ListSituation @onDeleteSituation="deleteSituation" :class="{hidden_list:isUpdating}" :situations="situations" @onEditSituation="editSituation" />
Fait

2021-03-01 14:19 UTC, merki230 approved these changes

2021-03-01 14:20 UTC, merged