Add the filter - change-log feature
DRC-COVID19/stopcoronavirus.cd pull request #159
Opened 2021-03-04 14:42 UTC by pacyL2K19

2021-03-05 15:42 UTC, pacyL2K19 commented
# Update on the PR
- Update the filter logic on change log screen 
- Add Reset buttons on the datePicker componenent / ChangeLog Screen and PandemicStat screen image :point_down: 
![PRstopcovid](https://user-images.githubusercontent.com/61581306/110137978-c1eb6b00-7dd1-11eb-82f1-412445fe2ac8.png)

2021-03-08 10:05 UTC, merki230 requested changes

2021-03-08 10:46 UTC, pacyL2K19 commented on resources/js/dashboard/pages/administrator/changeLog/index.vue
> +          this.$notify({
Ca vient de m'aider al'insant pour le debug mais je l'avais mis sans prevoir que ca pourait m'etre utile
C'est enleve now

2021-03-10 13:12 UTC, merki230 approved these changes

2021-03-10 13:14 UTC, merged