Pandemics backend
DRC-COVID19/stopcoronavirus.cd pull request #170
Opened 2021-03-18 16:28 UTC by pacyL2K19

## The Aim of this PR

#### Backend Side
> This PR adds some missed features in the backend like 
- Pandemy controller, module, and resources: Added relationship between pandemy cases, provinces and health zones
- Province controller, module, and resources: Allows now to create, update and delete provinces from the dashboard 
- Health zones controllers module, and resources 
- Relationship between all of these elements
#### Frontend SIde
- The UI of the pandemy page that contains 
- > Form to create and update 
- > List to display [image 1]
- The state features prepared 
* Need to add API consumption
* Need to review the get health zones to feature in the backend

> Images bellow
![list provinces](https://user-images.githubusercontent.com/61581306/111660956-e2beb200-880e-11eb-9145-9dcd2d061461.png)
![health_zpne creation](https://user-images.githubusercontent.com/61581306/111660978-e7836600-880e-11eb-839b-8e9a204e03c1.png)
![delete prov](https://user-images.githubusercontent.com/61581306/111661005-eeaa7400-880e-11eb-959b-e3310fa3b885.png)
![create province](https://user-images.githubusercontent.com/61581306/111661038-f79b4580-880e-11eb-9b1b-d8326ac7c647.png)
![ui](https://user-images.githubusercontent.com/61581306/111661167-14d01400-880f-11eb-8a57-5dd9ba3439ce.png)

@merki230 :checkered_flag:

2021-03-24 11:02 UTC, merki230 requested changes

2021-03-24 11:02 UTC, merki230 commented on routes/api.php
> +Route::group(['prefix' => 'pandemy', 'middleware' => 'auth:dashboard'], function () {
Test bine que me middleware auth:dashboard marche bien

2021-03-24 11:02 UTC, merki230 commented on routes/api.php
> +  Route::get('/filter/health_zone', 'PandemicController@filter_by_health_zone');
les routes statique doivent être toujours avant celle dynmique

2021-03-24 11:02 UTC, merki230 commented on routes/api.php
> +    Route::get('/filter', 'HealthZoneController@filter');
les routes statique doivent être toujours avant celle dynmiqu

2021-03-24 11:37 UTC, pacyL2K19 commented on app/Http/Controllers/HealthZoneController.php
> +    public function health_zone(Request $request)
Elle est inutilisee, j'avais trouvE ca
Dans le PR qui suit j'ai corrigE ca

2021-03-24 11:38 UTC, pacyL2K19 commented on app/Http/Controllers/HealthZoneController.php
> +            $health_zones = HealthZone::orderBy('id', 'DESC')->paginate(15);
Noted

2021-03-29 09:03 UTC, closed without merging

2021-03-29 09:05 UTC, pacyL2K19 commented
[This](https://github.com/DRC-COVID19/stopcoronavirus.cd/pull/164) PR contains everything fixed about this branch